# Generated by Django 2.2.1 on 2020-08-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('v_member', models.IntegerField(default=True)),
                ('v_point', models.IntegerField(default=True)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'v_lists',
                'managed': False,
            },
        ),
    ]
