# Generated by Django 2.2.1 on 2020-08-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='works',
        ),
    ]
